#### 1、ndarray的维数

In [19]:
import numpy as np  
arr=np.array(5)
print(arr)
print("arr的维度",arr.ndim)

arr=np.array([1,2,3])
print(arr)
print("arr的维度",arr.ndim)

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("arr的维度",arr.ndim)


5
arr的维度 0
[1 2 3]
arr的维度 1
[[1 2 3]
 [4 5 6]]
arr的维度 2


#### 2、ndarray的同质性

In [20]:
arr=np.array([1,"hello"])  #不同数据类型强制转换
print(arr)

arr=np.array([1,1.5,-1])  #不同数据类型强制转换
print(arr)

['1' 'hello']
[ 1.   1.5 -1. ]


#### 3、ndarray的属性

In [21]:
import numpy as np  
arr=np.array(["1",'1','1'])
print(arr)
print("数组的形状",arr.shape)
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的数据类型",arr.dtype)
print("元素的转置\n",arr.T)
print("_____________")
arr=np.array([[1,2.5,3],[4,5,6]])
print(arr)
print("数组的形状",arr.shape)
print("数组的维度",arr.ndim)
print("元素的个数",arr.size)
print("元素的数据类型",arr.dtype)
print("元素的转置\n",arr.T)

['1' '1' '1']
数组的形状 (3,)
数组的维度 1
元素的个数 3
元素的数据类型 <U1
元素的转置
 ['1' '1' '1']
_____________
[[1.  2.5 3. ]
 [4.  5.  6. ]]
数组的形状 (2, 3)
数组的维度 2
元素的个数 6
元素的数据类型 float64
元素的转置
 [[1.  4. ]
 [2.5 5. ]
 [3.  6. ]]


#### 4、ndarray的创建

In [22]:
list1=[4,5,6]
arr=np.array(list1)
print(arr)
arr1=np.copy(arr)
print(arr1)
arr[0]=7
print(arr)

#预定义形状
#zeros
arr=np.zeros((2,3))  #两行三列 全0(float)
print(arr)
arr=np.zeros((10,),int)
print(arr)

#ones
arr=np.ones((2,3))  #两行三列 全1(float)
print(arr)
arr=np.ones((10,),int)
print(arr)

#empty
arr=np.empty((3,3))
print(arr)  #元素随机

#full
arr=np.full((3,4),2026)
print(arr)

#形状like
arr1=np.zeros_like(arr)
print(arr1)
arr2=np.ones_like(arr1,float)
print(arr2)

[4 5 6]
[4 5 6]
[7 5 6]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 1 1 1 1 1 1 1 1 1]
[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
#等差数列
arr=np.arange(1,10,2)  #区间左闭右开，步长为2
print(arr)

#等间隔数列
arr1=np.linspace(2,10,5,dtype=int)  #2、10为边界，5等分
print(arr1)
arr2=np.arange(2,11,2)
print(arr2)

#对数间隔数列
arr3=np.logspace(2,4,3,base=2,dtype=int) #2^2  2^3  2^4
print(arr3)

arr3=np.logspace(2,4,3,dtype=int) #base默认是10
print(arr3)

[1 3 5 7 9]
[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 4  8 16]
[  100  1000 10000]


#### 5、矩阵生成

In [24]:
#单位矩阵
arr=np.eye(5,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [25]:
#对角矩阵
arr1=np.diag([2,3,4,5])
print(arr1)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [26]:
#随机数组生成
#默认生成0——1之间的随机float数
arr=np.random.rand(2,3) #在2x3矩阵中
print(arr)
#生成[3,6)任意区间float
arr1=np.random.uniform(3,6,(2,3))
print(arr1)
#生成指定范围内的随机整数
print(f"[3,10)随机整数\n{np.random.randint(3,10,(2,3))}")

[[0.63876234 0.15681569 0.9692081 ]
 [0.97513309 0.0567024  0.26279304]]
[[3.61965381 3.79404644 3.6560175 ]
 [3.21972267 4.20332804 4.02512022]]
[3,10)随机整数
[[7 7 7]
 [6 4 3]]


In [27]:
#正态分布
print(f"{np.random.randn(2,3)}")

[[ 0.03816471 -0.87744236 -1.49335797]
 [ 1.1042772   0.28841071 -0.77194186]]


In [28]:
#设置随机种子
np.random.seed(30)  #类比MC地图种子
print(F"{np.random.randint(1,11,(3,3))}")

[[ 6  6  5]
 [ 8  3  6]
 [ 2  4 10]]


#### 6、ndarray的数据类型
    -bool -int  -float  -complex

In [29]:
arr=np.array([1,1.5,2,0],dtype="complex")
print(arr)

[1. +0.j 1.5+0.j 2. +0.j 0. +0.j]


#### 7、索引与切片

In [30]:
#一维
arr=np.random.randint(1,100,20)
print(arr)
print(arr[0])
print(arr[:])
print(arr[2:5:2])       #[),step
print(arr[slice(2,5,1)])
print(arr[arr>49])#bool索引
print(arr[(arr>10) & (arr<60)])
print(arr[(arr<=10) | (arr>=60)])

[ 8 66 50 46 62 36 19 19 77 17  7 63 28 47 46 65 63 12 16 24]
8
[ 8 66 50 46 62 36 19 19 77 17  7 63 28 47 46 65 63 12 16 24]
[50 62]
[50 46 62]
[66 50 62 77 63 65 63]
[50 46 36 19 19 17 28 47 46 12 16 24]
[ 8 66 62 77  7 63 65 63]


In [31]:
arr2=np.random.randint(1,100,(4,5))
print(arr2)
print(arr2[1][3])
print(arr2[1][:])
print(arr2[1][1:3])

print(arr2[arr2>50])    #输出1维数组
print(arr2[0][arr2[0]>50])

[[14 51 34 56 29]
 [59 92 79 58 76]
 [96 45 38 76 58]
 [40 10 34 48 40]]
58
[59 92 79 58 76]
[92 79]
[51 56 59 92 79 58 76 96 76 58]
[51 56]


#### 8、ndarray的运算

In [32]:
#一维
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b,a-b)  #按位对应运算
print(a*b,a/b)
print(a**2)

[ 6  8 10 12] [-4 -4 -4 -4]
[ 5 12 21 32] [0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]


In [33]:
#二维
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(A+B)
print(A-B)
#矩阵与标量的运算
print(A+3)  
print(A**2)

[[ 2  2  3]
 [ 4  6  6]
 [ 7  8 10]]
[[0 2 3]
 [4 4 6]
 [7 8 8]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [34]:
#广播机制
a=np.array([1,2,3]) #1*3
b=np.array([[4],[5],[6]])  #3*1
print(a+b)

#不能广播的例子
a=np.array([1,2,3]) #1*3
b=np.array([4,5]) #1*2
# print(a+b)  will be error

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [35]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(A*B)  #矩阵的相应位置数量乘法结果
print(A@B)  #矩阵乘法


[[1 0 0]
 [0 5 0]
 [0 0 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 9、Numpy常用函数
##### 9.1基本数学函数

In [36]:
#计算平方根x^1/2
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
#计算指数e^x
print(np.exp(1))
print(np.exp(0))
#计算自然对数lnx
print(np.log(2.718281828459045))
#计算正弦值余弦值sinx cosx
print(np.sin(np.pi/2))
print(np.cos(np.pi))
#计算绝对值
print(np.abs([1,-1,2,-2,3,-3]))
#计算a的b次幂
print(np.power([-1,2,3],3))
#三种整除
a=np.array([0.2,0.5,0.6]) #浮点数误差会导致0.5四舍五入出错
print(np.round(a))
print(np.ceil(a))
print(np.floor(a))

3.0
[1. 2. 3.]
2.718281828459045
1.0
1.0
1.0
-1.0
[1 1 2 2 3 3]
[-1  8 27]
[0. 0. 1.]
[1. 1. 1.]
[0. 0. 0.]


##### 9.2统计函数

求和 求平均值 求中位数 求标准差 求方差

求最值 求分位数 求累积和 求累积差  

In [89]:
arr=np.random.randint(1,20,8) #[1,19]
arr.sort()
print(arr)

[ 1  2  2  3  6  7 12 13]


In [91]:
print(F"和:{np.sum(arr)}")
print(F"平均值:{np.mean(arr)}")
print(F"中位数:{np.median(arr)}")   #先排序，再看奇偶
print(F"标准差:{np.var(arr)}")
print(F"方差:{np.std(arr)}")
print(F"最大值:{np.max(arr)},最大值索引:{np.argmax(arr)}")
print(F"最小值:{np.min(arr)},最小值索引:{np.argmin(arr)}")
#分位数
print(F"0%分位数:{np.percentile(arr,0)}")
print(F"20%分位数:{np.percentile(arr,20)}")
print(F"50%分位数:{np.percentile(arr,50)}")
print(F"70%分位数:{np.percentile(arr,70)}")

和:46
平均值:5.75
中位数:4.5
标准差:18.9375
方差:4.351723796382303
最大值:13,最大值索引:7
最小值:1,最小值索引:0
0%分位数:1.0
20%分位数:2.0
50%分位数:4.5
70%分位数:6.8999999999999995


In [93]:
a=np.array([1,2,3,4])
print(F"前缀和:{np.cumsum(a)}")
print(F"前缀积:{np.cumprod(a)}")

前缀和:[ 1  3  6 10]
前缀积:[ 1  2  6 24]


##### 9.3比较函数

In [103]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([1,2,2,4,5,5,5])
print(F"是否大于4:{np.greater(a,4)}")
print(F"是否小于4:{np.less(a,4)}")
print(F"是否等于4:{np.equal(a,4)}")
print(F"a=b?:{np.equal(a,b)}")  #逐项比较
print(F"a<b?:{np.less(a,b)}")  #逐项比较

是否大于4:[False False False False  True  True  True]
是否小于4:[ True  True  True False False False False]
是否等于4:[False False False  True False False False]
a=b?:[ True  True False  True  True False False]
a<b?:[False False False False False False False]


In [112]:
#逻辑 与 或 非 异或
a=np.array([1,0])
b=np.array([1,1])
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a))
print(np.logical_xor(a,b))
#检查元素是否至少有一个true
print(np.any([1,0,1,0,1]))
print(np.any([0,0,0,0,0]))
#检查元素是否全为true
print(np.all([1,1,1,1]))

[ True False]
[ True  True]
[False  True]
[False  True]
True
False
True


In [127]:
#自定义条件 np.where(条件,符合条件可取区间,不符合条件可取区间)
arr=np.array([1,2,3,4,5])
print(np.where(arr<3,arr,[0]))
np.random.seed(11)
score=np.random.randint(40,100,10)
print(score)
print(np.where(score>=60,'及格','不及格'))  #三目运算符
print(np.where(score<60,'不及格',np.where(score<80,'良好','优秀')))
print(np.select([score>80,(score>=60) & (score<=80),score<60],['优秀','良好','不及格'],default='nan'))

[1 2 0 0 0]
[65 56 67 57 95 53 52 73 47 58]
['及格' '不及格' '及格' '不及格' '及格' '不及格' '不及格' '及格' '不及格' '不及格']
['良好' '不及格' '良好' '不及格' '优秀' '不及格' '不及格' '良好' '不及格' '不及格']
['良好' '不及格' '良好' '不及格' '优秀' '不及格' '不及格' '良好' '不及格' '不及格']


##### 9.4排序函数

In [ ]:
#排序
np.random.seed(20)
arr=np.random.randint(1,100,10)
print(arr)
print(np.sort(arr))
print(np.argsort(arr))#排序后对应索引

#去重
print(np.unique(arr))
#数组的拼接
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.concatenate((arr1,arr2)))
#数组的分割
print(np.split(arr,2)) #均分切割成两份
#调整数组形状
print(np.reshape(arr,[2,5]))

[91 16 96 29 91 10 21 76 23 72]
[10 16 21 23 29 72 76 91 91 96]
[5 1 6 8 3 9 7 0 4 2]
[10 16 21 23 29 72 76 91 96]
[1 2 3 4 5 6]
[array([91, 16, 96, 29, 91], dtype=int32), array([10, 21, 76, 23, 72], dtype=int32)]
[[91 16 96 29 91]
 [10 21 76 23 72]]
